
DROP TABLE Team CASCADE CONSTRAINTS;

DROP TABLE GamePlay CASCADE CONSTRAINTS;

DROP TABLE PlayerHas CASCADE CONSTRAINTS;

DROP TABLE Career CASCADE CONSTRAINTS;

DROP TABLE Coach CASCADE CONSTRAINTS;

DROP TABLE Attends CASCADE CONSTRAINTS;

DROP TABLE User_likeTeam CASCADE CONSTRAINTS;

DROP TABLE User_likePlayer CASCADE CONSTRAINTS;

DROP TABLE Users CASCADE CONSTRAINTS;