SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS Team CASCADE;

DROP TABLE IF EXISTS GamePlay CASCADE;

DROP TABLE IF EXISTS PlayerHas CASCADE;

DROP TABLE IF EXISTS Career CASCADE;

DROP TABLE IF EXISTS Coach CASCADE;

DROP TABLE IF EXISTS Attends CASCADE;

DROP TABLE IF EXISTS User_likeTeam CASCADE;

DROP TABLE IF EXISTS User_likePlayer CASCADE;

DROP TABLE IF EXISTS Users CASCADE;

SET FOREIGN_KEY_CHECKS=1;
